[project]
name = "multi-agent-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autogenstudio>=0.4.2.2",
    "groq>=0.29.0",
    "python-dotenv>=1.1.1",
]
